#!/usr/bin/env python

import curses
import atexit


# set up terminal
stdscr = curses.initscr()
curses.noecho()
curses.cbreak()
stdscr.keypad(True)
try:
    curses.curs_set(0)
    curses.start_color()
except:
    pass

# reset terminal up on exit
atexit.register(lambda: (
    curses.echo(),
    curses.nocbreak(),
    stdscr.keypad(False),
    curses.endwin()
))

# stdscr.border()

# initialize bounds and position
max_y, max_x = (p - 1 for p in stdscr.getmaxyx())
min_x, min_y = 0, 0
x, y = min_x, min_y
stdscr.move(y, x)

# draw loop
while True:
    try:
        stdscr.addstr(y, x, "█")
    except:
        pass

    stdscr.move(y, x)

    key = stdscr.getkey()

    match key:
        case "w":
            y = max(y - 1, 1)
        case "a":
            x = max(x - 1, 1)
        case "s":
            y = min(y + 1, max_y)
        case "d":
            x = min(x + 1, max_x)
