#!/usr/bin/env python

import curses
from typing import Self
from contextlib import AbstractContextManager


class Renderer(AbstractContextManager):
    def __enter__(self):
        # set up terminal
        self.stdscr = curses.initscr()
        curses.noecho()
        curses.cbreak()
        self.stdscr.keypad(True)
        try:
            curses.curs_set(0)
            curses.start_color()
        except:
            pass

        # initialize bounds
        self.max_y, self.max_x = (p - 1 for p in self.stdscr.getmaxyx())
        self.min_x, self.min_y = 0, 0

        self.x, self.y = self.min_x, self.min_y
        self.stdscr.move(self.y, self.x)

        return self

    def __exit__(self, *_):
        # reset terminal on exit
        curses.echo()
        curses.nocbreak()
        self.stdscr.keypad(False)
        curses.endwin()

    def read_input(self):
        key = self.stdscr.getkey()

        match key:
            case "w":
                self.y = max(self.y - 1, self.min_y)
            case "a":
                self.x = max(self.x - 1, self.min_x)
            case "s":
                self.y = min(self.y + 1, self.max_y)
            case "d":
                self.x = min(self.x + 1, self.max_x)

    def render(self):
        try:
            self.stdscr.addstr(self.y, self.x, "█")
        except:
            pass

        self.stdscr.move(self.y, self.x)


with Renderer() as renderer:
    while True:
        renderer.render()
        renderer.read_input()
