#!/usr/bin/env python

import curses
from contextlib import AbstractContextManager
import random
import time


class Renderer(AbstractContextManager):
    """Context manager for drawing to the terminal"""

    table = [
        " ", "🮢", "🮣", "─",
        "🮡", "🮨", "│", "🮠",
        "🮠", "│", "🮩", "🮡",
        "─", "🮣", "🮢", " "
    ]
    """Look up table for marching squares"""

    def __enter__(self):
        # set up terminal
        self.stdscr = curses.initscr()
        curses.noecho()
        curses.cbreak()
        self.stdscr.keypad(True)
        try:
            curses.start_color()
        except:
            pass

        # initialize canvas and position
        max_y, max_x = self.stdscr.getmaxyx()
        self.canvas = [[False for _ in range(max_y)] for _ in range(max_x)]
        self.x, self.y = 0, 0

        return self

    def __exit__(self, *_):
        # reset terminal
        curses.echo()
        curses.nocbreak()
        self.stdscr.keypad(False)
        curses.endwin()

    def read_input(self):
        """Wait for input and update canvas accordingly"""

        key = self.stdscr.getkey()

        match key:
            case "w":
                self.y = max(self.y - 1, 0)
            case "a":
                self.x = max(self.x - 1, 0)
            case "s":
                self.y = min(self.y + 1, len(self.canvas[0]) - 1)
            case "d":
                self.x = min(self.x + 1, len(self.canvas) - 1)
            case " ":
                self.clear()

        self.canvas[self.x][self.y] = True

    def render(self, refresh: bool = False):
        """Render canvas using marching squares"""

        for i in range(len(self.canvas) - 1):
            for j in range(len(self.canvas[0]) - 1):
                x = 0
                if self.canvas[i][j + 1]:
                    x += 1
                if self.canvas[i + 1][j + 1]:
                    x += 2
                if self.canvas[i + 1][j]:
                    x += 4
                if self.canvas[i][j]:
                    x += 8

                try:
                    self.stdscr.addstr(j, i, Renderer.table[x])
                except:
                    pass

        if refresh:
            self.stdscr.refresh()

    def clear(self):
        for p in range(20):
            for i in range(len(self.canvas)):
                for j in range(len(self.canvas[0])):
                    if self.canvas[i][j] == True and \
                            random.randrange(20) < p + 1:
                        self.canvas[i][j] = False

            self.render(True)
            time.sleep(0.02)


with Renderer() as renderer:
    while True:
        renderer.render()
        renderer.read_input()
